Update index.en.md vers index.fr.md
jujudusud/ardour-tutorial pull request #1
Opened 2023-10-22 12:22 UTC by cyrilger

Première proposition de taduction de l'anglais vers le français de la page dynamics/index.en.md

2023-10-22 16:50 UTC, jujudusud commented
Salut Cyril,

C'est parfait !
J'ai pas grand chose d'autre à dire.

Enfin, si ! C'est un super début. Je vois que tu as traduit un premier document. Je vais faire une revue en écrivant ce que je vois comme amélioration possible comme ça on pourra en parler.

Pour la suite, tu peux pousser (push) un autre fichier quand tu veux, il tombera au même endroit, ici si tu le mets dans la même branche, celle qui s'appelle "patch-1" chez toi.

Dès que j'ai un moment j'attaque la revue. Merci déjà pour tout ça ! :-)

2023-10-23 21:39 UTC, jujudusud requested changes

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Ce genre de problème ne peut pas être facilement résolu en utilisant uniquement les faders pour ajuster les niveaux.
Pour "faders", on traduira par "atténuateurs".

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Il y a plusieurs types d'outils pour ajuster la plage dynamique en général disponibles en tant que greffons externe à Ardour, dont notemment _limitation_, _compression_ et _gating_.
notemment -> notamment
"gating" en anglais se traduira par "déclenchement"

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Un limiteur peut-être utilisé sur le bus _Master_ pour empêcher l'ensemble du mix de saturer. Les limiteurs sont quasiment toujours utilisés post-fader.
fader -> atténuateur

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Alors que la réduction du volume est quasi instantanée, le réglage _Release time (s)_ (temps de relâche) détermine la durée mise par le limiteur pour retourner au 0dB de l'_Attenuation_.
Je sais que "quasi" est très utilisé. Mais on preferera "quasiment".

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Sur le bus _Master_, il est généralment mieux d'éviter une limitation excessive.
généralement, il manque un "e".

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Un compresseur type aura obligatoirement ces contrôles:
En français, on doit mettre un espace insécable avant les deux points.

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Le greffon _ACE Compressor_ sur la capture d'écran ci-dessous a deux contrôles en plus:
ci-dessus

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +La forme la plus simple d'un _gate_ (porte) autorise un signal à passer au travers au dessus d'un certain niveau et bloque le signal lorsqu'il est en deça de ce niveau.
porte -> déclencheur ?

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Les "gates" sont souvent utilisés pour faire office de réducteur de bruit. Par exemple, un gate sur la piste d'un piste microphone pourrait s'ouvrir uniquement lorsque le/la chanteur.euse chante, ce
"sur la piste d'un microphone" répétition de "piste"
pas d'écriture inclusive. -> "lorsque le chanteur ou la chanteuse chante" ou bien "lorsque le chanteur (la chanteuse) chante.

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +[CMT](https://www.ladspa.org/cmt/overview.html)) qui présente un seul paramètre de contrôle: le _Threshold_  (seuil) à partir duquel le "gate" va s'ouvrir et laisser passer le signal.
supprimer un espace avant "(seuil)"

2023-10-23 21:39 UTC, jujudusud commented on content/mixing-sessions/dynamics/index.en.md
> +Maintenant que nous avons exploré quelques outils pour positionner la plage dynamique là où vous le souhaitez, il est temps de procéder au réglage la balance des fréquences présentes dans chaque pist
au réglage **de** la balance ... individuelle **et** dans votre mix

2023-10-26 18:54 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Ce genre de problème ne peut pas être facilement résolu en utilisant uniquement les faders pour ajuster les niveaux.
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Maintenant que nous avons exploré quelques outils pour positionner la plage dynamique là où vous le souhaitez, il est temps de procéder au réglage la balance des fréquences présentes dans chaque pist
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +[CMT](https://www.ladspa.org/cmt/overview.html)) qui présente un seul paramètre de contrôle: le _Threshold_  (seuil) à partir duquel le "gate" va s'ouvrir et laisser passer le signal.
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Les "gates" sont souvent utilisés pour faire office de réducteur de bruit. Par exemple, un gate sur la piste d'un piste microphone pourrait s'ouvrir uniquement lorsque le/la chanteur.euse chante, ce
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +La forme la plus simple d'un _gate_ (porte) autorise un signal à passer au travers au dessus d'un certain niveau et bloque le signal lorsqu'il est en deça de ce niveau.
On essaye avec ça...
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Le greffon _ACE Compressor_ sur la capture d'écran ci-dessous a deux contrôles en plus:
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Un compresseur type aura obligatoirement ces contrôles:
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Sur le bus _Master_, il est généralment mieux d'éviter une limitation excessive.
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Alors que la réduction du volume est quasi instantanée, le réglage _Release time (s)_ (temps de relâche) détermine la durée mise par le limiteur pour retourner au 0dB de l'_Attenuation_.
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Un limiteur peut-être utilisé sur le bus _Master_ pour empêcher l'ensemble du mix de saturer. Les limiteurs sont quasiment toujours utilisés post-fader.
Supprimer: "de cette façon"
Fait.

2023-10-26 19:02 UTC, cyrilger commented on content/mixing-sessions/dynamics/index.en.md
> +Il y a plusieurs types d'outils pour ajuster la plage dynamique en général disponibles en tant que greffons externe à Ardour, dont notemment _limitation_, _compression_ et _gating_.
Fait.

2023-10-26 21:04 UTC, merged